### ISSUE TITLE
IOS height auto animation flickering

### ISSUE THREAD

**Issue by kuzyo** [Stanko/react-animate-height#10]
When animating form 0 to auto you can see content flickeirng. Reproduced on IOS9 Chrome, Safari. Desktop works ok.
Please check the demo: 
[AnimateHeight.zip](https://github.com/Stanko/react-animate-height/files/1044094/AnimateHeight.zip)

**Comment by Stanko** [comment]
Hello @kuzyo,I think I got it, I'll push the fix soonish. I'm testing on browserstack, which is really annoying.

**Comment by Stanko** [comment]
This should be fixed in version 0.9.5, check the commit https://github.com/Stanko/react-animate-height/commit/bf20e5ba2f9ddc44011c6870d9f024d1e9e7b48c

Although I would appreciate if you can test it on a real device @kuzyo 

Thanks!

**Comment by kuzyo** [comment]
Thank you for so fast fix. Will write feedback after testing.

**Comment by Stanko** [comment]
@kuzyo can you please confirm if this is working now?

**Comment by kuzyo** [comment]
Works for me. Don't have any reports.

**Comment by Stanko** [comment]
Great, I'm closing it then. Thanks!
