### ISSUE TITLE
Allow scroll if the height is less than the maximum height

### ISSUE THREAD

**Issue by tqdo** [Stanko/react-animate-height#103]
This package is awesome. I am playing around with the demos here: https://muffinman.io/react-animate-height/ and wonder whether there is any way to scroll to see the full content if the chosen height is less than the actual height (when we set height to 'auto'). Thanks

**Comment by Stanko** [comment]
Hey, thank you!

You can do something like this:
```jsx
<AnimateHeight height={isOpen ? "auto" : 0}>
  <div
    style={{
      width: 300,
      overflow: "auto",
    }}
  >
    Content goes here...
  </div>
</AnimateHeight>
```

Add a scrolling div inside `AnimateHeight` and then limit it's height.

Check demo here:
https://codesandbox.io/s/quirky-turing-hn2vx?file=/src/App.js

Cheers!
