### ISSUE TITLE
IE overflow:hidden animating from 0 to auto

### ISSUE THREAD

**Issue by iaanvn** [Stanko/react-animate-height#11]
In IE 10, when animating from 0 to auto, `overflow:hidden` is applied to the div containing "demo-content", not the "rah-static" div. When height is toggled, `overflow:visible` is not applied again, rather `overflow:hidden` is just removed.  You can see this on https://stanko.github.io/react-animate-height/#demo also.

In the demo, this is not causing an issue, but this is an issue where we are using absolutely positioned content inside the <AnimateHeight / > component. Without `overflow:visible`, the absolutely positioned content is cut off where the height exceeds the container div with `height: auto`

**Comment by Stanko** [comment]
Hello @iaanvn,
Yes, you are right, I made a mistake here:
https://github.com/Stanko/react-animate-height/blob/master/src/AnimateHeight.js#L56

It works on other browsers, but IE doesn't cooperate. I will fix it and publish to npm soon.

**Comment by Stanko** [comment]
Fixed in version 0.9.5, check the commit https://github.com/Stanko/react-animate-height/commit/bf20e5ba2f9ddc44011c6870d9f024d1e9e7b48c
