### ISSUE TITLE
Webpage is inaccurate about dependencies

### ISSUE THREAD

**Issue by kzahel** [Stanko/react-animate-height#112]
Your webpage says "Lightweight, no dependency React component for animating height using CSS transitions"

This isn't exactly true. You are using `classnames` as a dependency.

**Comment by Stanko** [comment]
That's super olf leftover :) I'll remove it.

**Comment by Stanko** [comment]
Fixed in [this commit](https://github.com/Stanko/react-animate-height/commit/839ca15903a8286602133ce2c11a5ec2eed50497#diff-b04b38d4e36f7a7171aeb211bf933eaf36d41d9866ebbc3639f673f84dc350aeR34).
