### ISSUE TITLE
Add `aria-hidden` attribute for accesibility

### ISSUE THREAD

**Issue by NeonPaul** [Stanko/react-animate-height#12]
Please add `aria-hidden="true"` when the component has height=0 so the content is not read by assistive technology

**Comment by Stanko** [comment]
Hello @NeonPaul, good catch, when I get to this one, should I consider adding something else for accessibility.

**Comment by Stanko** [comment]
Fixed in this commit https://github.com/Stanko/react-animate-height/commit/23aa3955cddf05f90a3be18afd37bd34dd1516f1
