### ISSUE TITLE
React 18 (in StrictMode): Uncaught TypeError: Cannot read properties of null (reading 'animating') 

### ISSUE THREAD

**Issue by josephmarkus** [Stanko/react-animate-height#123]
`react-animate-height` blows up in React 18. The library is used for an accordion component that animates on state toggle.

**Code example**
https://codesandbox.io/s/lingering-wood-tjnu2k?file=/src/App.js

**Expected behavior**

Clicking 'Open' should expand the component that is wrapped with `<AnimateHeight />`. Instead, it blows up

**Possible Solution**

🤷‍♂️ 😅 

**Steps to Reproduce (for bugs)**

1. Go to https://codesandbox.io/s/lingering-wood-tjnu2k?file=/src/App.js
2. Click 'Open'
3. Observe the error

**Screenshots**

![6eb58856-55b0-4e4c-9192-52381e025f3b](https://user-images.githubusercontent.com/9258365/162959025-d31df5a5-9cfa-4ea9-9707-ecf7574a3010.png)

**Your Environment**
 - Version used: 2.0.23
 - OS: MacOS
 - Browser: Chrome
 - Version: 100.0.4896.75

**Additional context**

n/a

**Comment by Stanko** [comment]
Hello, thanks for letting me know. It seems it blows up when `StrictMode` is enabled. I'll look into it.
Cheers!

**Comment by Stanko** [comment]
Fixed in 2.1.0 🎉 

Example:
https://codesandbox.io/s/ecstatic-leaf-x652u4
