### ISSUE TITLE
Version 2.1.1 - matchMedia is not defined

### ISSUE THREAD

**Issue by ritabazak** [Stanko/react-animate-height#125]
After upgrading to 2.1.1, we are getting an error that matchMedia is not defined in AnimateHeight.js.
We are using react 16.14.0.

**Comment by Stanko** [comment]
Hello,
Which browser or environment? 

Btw AnimateHeight doesn't support super old browsers that do not support it:
https://caniuse.com/?search=matchMedia

**Comment by johnhunter** [comment]
Also seeing this in jest tests

```
jest@27.5.1
jsdom@16.7.0
```

We have a check for `window.matchMedia` elsewhere in our code and this does not fail
```
  if (!('matchMedia' in window)) {
    throw new Error('`window.matchMedia` is not supported by this browser');
  }
```

**Comment by Stanko** [comment]
I just pushed 2.1.2 with the explicit check if `matchMedia` exists. Can you please confirm it works because I can't reproduce this locally. Thanks!

**Comment by johnhunter** [comment]
Will do, thanks.

**Comment by johnhunter** [comment]
That looks to have fixed my issues with Jest tests. Thanks for the quick turnaround! 🎉

**Comment by ritabazak** [comment]
Yes, we saw the issue in the tests, we are using:
```
enzyme@3.11.0
jsdom@11.12.0
jest@24.9.0
```
Will try now the fix as well, thank you :)
