### ISSUE TITLE
Margin on content of accordion causes small jump at the end of animation

### ISSUE THREAD

**Issue by Hahlh** [Stanko/react-animate-height#128]
Good day! Thanks for the awesome package. 

Additional margin on the children of `<AnimateHeight>` seems to cause a noticable 'jump' at the end of the animation.  

I created a video for you here as this should be the easiest and most effective way of showing the behavior:

https://user-images.githubusercontent.com/45669613/170217312-1885109e-ca61-4524-b7c6-ac9731f7eda4.mp4

Being able to keep using margin in those place would be important for basic text styling. 

I will test whether the behavior also occurs after building (Gatsby & Tailwind are used). 

Interestingly padding doesn't seem to trigger the issue.

Do you need any other information?

**Comment by Stanko** [comment]
Hey @Hahlh,
Thanks for the detailed description. Unfortunately, due to margins collapsing it is not possible to use margins in this scenario. But you can switch to padding and the issue won't happen. Hope that helps.
Cheers!

**Comment by Hahlh** [comment]
Okay great! That should likely be mentioned in the readme. 

Thank you for the fast answer @Stanko ! :slightly_smiling_face:

**Comment by Stanko** [comment]
You are right, I'm going to add a paragraph in "Gotchas", thanks!
