### ISSUE TITLE
Better 'Usage' in README

### ISSUE THREAD

**Issue by podrivo** [Stanko/react-animate-height#13]
It's not clear you have to use set states in order to animate.
I had to check example.js and discover you have to use `this.setState({ height: 'auto' })`.

Maybe a more detailed usage would be better for noobies like myself! (:

**Comment by Stanko** [comment]
Hello,
That's basically how react works. To re-render the component I'm updating the state. ATM I'm travelling, but I can do a blog post how it works when I get back. How does that sound?

**Comment by podrivo** [comment]
Sounds awesome, man! I got it working, though. But this sounds like a great idea for new comers! (:

**Comment by jklegseth** [comment]
Blog post is great but I agree with @podrivo, why not include it in the documentation? Maybe just update your example to include it? Happy to do a PR if it's helpful.

```
class Example extends Component {
  state = {
    height: 0
  };

  toggle = () => {
    this.setState({
      height: !this.state.height ? 'auto' : 0
    });
  };

  render() {
    return (
      <div>
        <button onClick={this.toggle}>
          {!this.state.height ? 'Open' : 'Close'}
        </button>

        <AnimateHeight
          duration={500}
          height={this.state.height} // see props documentation bellow
        >
          <h1>Your content goes here</h1>
          <p>Put as many React or HTML components here.</p>
        </AnimateHeight>
      </div>
    );
  }
}
```

**Comment by podrivo** [comment]
@jklegseth You should do the PR! (:

**Comment by Stanko** [comment]
Hey,
I've updated the [readme](https://github.com/Stanko/react-animate-height/blob/master/README.md#quick-start) with the example you provided.

I'm really busy with other projects, but I have this on my todo list.

Cheers!

**Comment by Stanko** [comment]
This never re-surfaced and library has over half a million downloads a month. I'm pretty sure it is safe to close.
