### ISSUE TITLE
Doesn't work on Chrome Version 106.0.5249.103 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by FatemiParsHost** [Stanko/react-animate-height#130]
Hi dear developer 
I was used this package on my project and doesn't work on chrome in desktop  PC and i test on ipad its fixed pls fix this problems on windows OS thanks ♥

**Comment by Stanko** [comment]
Hi @FatemiParsHost,
I've just tried it on both windows (through Browserstacl) and on mac, and everything seems to be working fine:

| Windows, Chrome 106.0.5249.21 | MacOS (arm) Chrome 106.0.5249.103 |
|-|-|
| <video src="https://user-images.githubusercontent.com/776788/194703376-42f06853-0d99-45b4-addc-bdf61090fe9f.mp4" /> | <video src="https://user-images.githubusercontent.com/776788/194703518-f56f18ac-6cfd-484c-bcbe-cc892b3b97ff.mp4" /> |

Please check if you maybe have [reduced motion](https://github.com/Stanko/react-animate-height#reduced-motion) turned on.

I would need a code example (on [codesandbox](https://codesandbox.io/) or similar) or at least a video of what is happening.

Cheers!

**Comment by FatemiParsHost** [comment]
Hi Dear @Stanko 
I check it again and check reduced motion but doesn't work
but let me check on other OS and tell you 

Thanks Mate

**Comment by Stanko** [comment]
Closing this as I can't replicate it.
