### ISSUE TITLE
Animation does not seem to work in my app or in the official sandbox

### ISSUE THREAD

**Issue by U-4-E-A** [Stanko/react-animate-height#131]
Title says it all, really. I recently moved from v2 to v3 to find the animation does not work in my app. It appears that the animation also does not work on the official sandbox: -

https://codesandbox.io/s/react-animate-height-v3-basic-example-1iggpe

It is acting as though there is a `duration` of `0`. I have tried it in Chrome, FF and Brave... none work. Am I missing something here? Thanks.

**Comment by Stanko** [comment]
Hello @U-4-E-A,

I've just tried the sandbox you linked and it works fine in both firefox and chrome:

|Firefox|Chrome|
|-|-|
|<video src="https://user-images.githubusercontent.com/776788/200930035-60bd3a18-2276-4c76-b5e8-0e03f6b191a0.mov" />|<video src="https://user-images.githubusercontent.com/776788/200930073-7cf32333-2f8a-4ff5-b365-f9f27d5538db.mov" />|

Do you maybe have [reduced motion](https://github.com/Stanko/react-animate-height#reduced-motion) turned on?

**Comment by U-4-E-A** [comment]
You're correct. Oddly, v2 worked out with animations turned off. Thanks.
