### ISSUE TITLE
import not allowed in non-module files

### ISSUE THREAD

**Issue by awdyson** [Stanko/react-animate-height#143]
It appears a `package.json` with `"type": "module"` was removed from `dist/esm`.
Looks like you replaced piping an `echo` into a new file with a `post-build script -- then removed the script. 

**Possible Solution**
The old `echo` statement worked, and I'm going to guess the `post-build` script worked as well.
Alternatively, you could name the file `index.mjs`.

**Screenshots**
![image](https://github.com/Stanko/react-animate-height/assets/5612248/10b95384-f935-4de9-b1a7-826031298892)

**Comment by Stanko** [comment]
Hi @awdyson,

I removed two package.json files to resolve this issue:
https://github.com/Stanko/react-animate-height/issues/140

But broke this in the process. There is so many use-cases in JS world to cover today. I’ll try renaming the file later today and hopefully that will fix it.

Cheers!

**Comment by Stanko** [comment]
Can you please tell me which setup are you using? I can't replicate the issue on my side, so I want to be sure I'm fixing the right thing. Thanks!

**Comment by Stanko** [comment]
I just published v3.2.2 which I hope will resolve the issue. Please let me know if it works.

**Comment by awdyson** [comment]
Yep, that solution works for my setup, thank you very much.

---

> There is so many use-cases in JS world to cover today.

You are not kidding 😶
