### ISSUE TITLE
Module 'prop-types' not found

### ISSUE THREAD

**Issue by rs-tiwen** [Stanko/react-animate-height#15]
Bug: when using with react-scripts, after install I got the following error:
```
Failed to compile.

Error in ./~/react-animate-height/lib/AnimateHeight.js
Module not found: 'prop-types' in /Users/tiwen/www/rscience/rsui-app/node_modules/react-animate-height/lib

 @ ./~/react-animate-height/lib/AnimateHeight.js 20:16-37
```

it appears to be that this module needs `prop-types`, we might want to move 'prop-type' from devDependency to dependency in the package.json?

**Comment by Stanko** [comment]
Hello, I could swear that I already moved it. Sorry my bad, fixed here: https://github.com/Stanko/react-animate-height/commit/e71c3ac11917731132474f9de5433b942ada3805

Released on npm as well

**Comment by rs-tiwen** [comment]
Thanks for the ultra-fast response!
and thanks for great design on the simplicity of this component's API!

**Comment by Stanko** [comment]
You are welcome, thanks for the kind words!
