### ISSUE TITLE
Potential breaking change with 0.9.10

### ISSUE THREAD

**Issue by aabenoja** [Stanko/react-animate-height#17]
We have some test failures around `AnimateHeight.hideContent(height)` call in [`componentDidMount`](https://github.com/Stanko/react-animate-height/blob/e52a3b9098e37b4bf4ddd7ce46022643de41156f/src/AnimateHeight.js#L71).

```
    TypeError: Cannot read property 'style' of null
      
      at AnimateHeight.hideContent (node_modules/react-animate-height/lib/AnimateHeight.js:248:28)
      at AnimateHeight.componentDidMount (node_modules/react-animate-height/lib/AnimateHeight.js:99:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:263:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:209:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:156:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:143:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render [as create] (node_modules/react-test-renderer/lib/ReactTestMount.js:128:18)
```

Here's a snippet of our current usage of `AnimateHeight`

```jsx
<AnimateHeight
  aria-labelledby={headingAriaId}
  duration={300}
  height={isActive ? 'auto' : 0}
  id={regionAriaId}
  role="region"
/>
```

It looks like `hideContent()` and `showContent` rely on `style` to be present on the `contentElement`, which may not always be there especially on mount in a headless test setting. Should there be some form wait until the DOM element has a style property before acting on it?

**Comment by Stanko** [comment]
Hello,
`componentDidMount` in react lifecycle is triggered after the component is rendered to dom. I will look into it, but not sure when I'll catch time to do it.

**Comment by aabenoja** [comment]
In fact, we are using enzyme with jest and jsdom, but thank you for the suggestion.

**Comment by Stanko** [comment]
@aabenoja that makes much more sense, thanks for the info. Do you have any suggestions how to solve it?

I can add old school

```js
if (this.contentElement && this.contentElement.style) {
  this.contentElement.style.display = 'none';
}
```

but more elegant fix would be nice.

If nothing comes to mind, I can patch like this so it doesn't break tests.

**Comment by aabenoja** [comment]
The frustrating thing is that this only affects any project feeding this component into the `react-test-renderer`. Admittedly I can't think of much better at the moment, though I'm starting to think we don't need to modify `showContent()` or `hideConent()`. Since this only seems to affect the renderer during the mounting process we might be able to get away with the check being only in `componentDidMount()`. Let me give that a shot locally and report back.

**Comment by aabenoja** [comment]
@Stanko Good news! We can get away with having the `this.contentElement.style` check in `componentDidMount` without doing that every `showContent()` or `hideContent()` call.

The downside is we've found one of our tests failing because it can't find `requestAnimationFrame` when it rerenders because of prop change. It could be "fixed" on this end by using a noop when `window.requestAnimationFrame` is undefined, but I'm leaning towards having the users polyfill that global themselves.

**Comment by Stanko** [comment]
Great! I just pushed new version to npm

You can see commit here: https://github.com/Stanko/react-animate-height/commit/a8361ffc7f2324ea387ccef91ae5ff49c2fedcfa

I agree that `requestAnimationFrame` should be polyfilled on their side. 

Please check if this fixes issue for you, so we can close the issue.

**Comment by aabenoja** [comment]
Awesome, everything is green again. The only thing to potentially followup on is documenting the need to polyfill `requestAnimationFrame`. Thank you for your help.

To answer your question, we're using `react-animate-height` in out company's [style guide](https://github.com/TWExchangeSolutions/es-components). Your component has been a great help!

**Comment by Stanko** [comment]
You are welcome! Thanks, glad to hear that.

**Comment by mikeaustin** [comment]
Sorry to reply to an old ticket, but I wanted to mention an issue when using AnimateHeight with Preact. I've recently created a ticket to see what they say about it:

Problems with Preact and AnimateHeight component
https://github.com/developit/preact/issues/1057

It boils down to Preact maybe doing some element recycling and setting display to 'none' is not getting undone.

**Comment by mikeaustin** [comment]
The recycling / re-use issue came up again in another area. A coworker solved it by adding a componentWillReceiveProps() that does the same thing as the constructor. The elements are not shared and should be completely different instances, but somehow Preact is re-using them.

**Comment by Stanko** [comment]
So any ideas how should we tackle that? Sorry, but I have no experience with Preact.

**Comment by aabenoja** [comment]
Maybe make an example repo to reproduce the issue @mikeaustin?
