### ISSUE TITLE
Update build script for node v8

### ISSUE THREAD

**Issue by aabenoja** [Stanko/react-animate-height#18]
Currently your build script down not work with node v8. This is due to a handful of dependencies using `require.extensions`, which has been dropped. The latest versions of `require-dir` and `gulp-git` resolve this, but `react-component-gulp-tasks` still needs to be updated. I have not been able to determine if any other build dependency needs to updated for this reason.

As for `react-component-gulp-tasks` it is unclear if this will get resolved soon. While `require-dir` and `gulp-git` have both updated and resolved their node v8 compatibility issues, `react-component-gulp-tasks` currently has an [open issue and PR](https://github.com/JedWatson/react-component-gulp-tasks/issues/31). The project itself may be dead, as the last update to master was a little more than a year ago.

**Comment by Stanko** [comment]
Meh, I was searching for a better workflow for development and releasing react components, and in the end written my own. So I'll switch to that one soon.

You can see it in action here:
https://github.com/Stanko/react-plx

Thanks for pointing that out

**Comment by Stanko** [comment]
Replaced `react-component-gulp-tasks` with workflow I use on the other component and updated the documentation.
