### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by aristidesfl** [Stanko/react-animate-height#19]

**Comment by Stanko** [comment]
What does that even mean? 🙃 

You can't just open a issue with no description.

**Comment by aristidesfl** [comment]
I just did :D

divs can't be children of tables, tbody, tr elements, so table rows can't be animated currently.

**Comment by Stanko** [comment]
No they can't nor I'm planning to add support for that. What you are describing is accordion. It can easily done without animating tables themselves.

This is not really an issue.

**Comment by aristidesfl** [comment]
Wether to support it or not is up to you. But care to explain how you can animate table rows without animating the elements themselves?

**Comment by lakesare** [comment]
@Stanko, what he is describing is not an accordion, it's the <tr/> or <tbody/> tag heights animated, for which we'd need to have control of the tag `<AnimateHeight/>` wraps our code in.
I stumbled upon this issue now too.

**Comment by Stanko** [comment]
You can't animate tables easily due to their's specific HTML structure. And `AnimateHeight` has it's own specific structure which doesn't work with tables. But you can build accordion that looks like a table.

```jsx
import React, { Component } from "react";
import AnimateHeight from "react-animate-height";

import "./styles.css";

Something like:

export default class CollapsableRow extends Component {
  state = {
    isCollapsed: true
  };

  toggleIsCollapsed = () => {
    const { isCollapsed } = this.state;
    this.setState({
      isCollapsed: !isCollapsed
    });
  };

  render() {
    const { children, collapsableContent } = this.props;
    const { isCollapsed } = this.state;

    return (
      <div className="CollapsableRow">
        <div className="CollapsableRow-toggle" onClick={this.toggleIsCollapsed}>
          {children}
        </div>
        <AnimateHeight height={isCollapsed ? 0 : "auto"}>
          {collapsableContent}
        </AnimateHeight>
      </div>
    );
  }
}
```

And you can use it like this (`Row` and `Cell` are simple components you need to create):

```js

<CollapsableRow collapsableContent={
  <Row>
    <Cell>1</Cell>
    <Cell>2</Cell>
    <Cell>3</Cell>
  </Row>
  <Row>
    <Cell>1</Cell>
    <Cell>2</Cell>
    <Cell>3</Cell>
  </Row>
}>
  <Cell>1</Cell>
  <Cell>2</Cell>
  <Cell>3</Cell>
</CollapsableRow>

```

**Comment by lakesare** [comment]
@Stanko, I understand we could get rid of the table structure, but it has its own benefits (automatic column width scaling, reuse of existing CSS).
If we had a `tag="tbody"` prop for `<AnimateHeight/>`, and if we could get rid of the second inner `<div>` for certain cases, - then we'd be able to animate tables too.

**Comment by Stanko** [comment]
Unfortunately, the inner div is essential for the functionality.
