### ISSUE TITLE
Remove Inline Styles After Transition

### ISSUE THREAD

**Issue by ChrisSargent** [Stanko/react-animate-height#2]
I just put in a pull request to switch to request animation frame instead of timeouts.

In addition, it would be nice it this would only apply it's necessary inline styles during the transition.

e.g. I have some floated paragraphs that I use to this to expand but they should always have 'overflow: hidden' set on them to stop them wrapping under various other elements. In it's current form, this component leaves 'overflow: visible' as an inline style so I'm having to overwrite it with !important in css which is not ideal.

Is there some function it calls after the transitions are complete (that I could hook in to to remove the styles)?

Thanks!

Chris

**Comment by Stanko** [comment]
Thanks a lot, I will take a look. For some reason GitHub didn't subscribed me automatically on issues/prs.

**Comment by Stanko** [comment]
@ChrisSargent I could add support for callbacks, does that sound good?

**Comment by ChrisSargent** [comment]
That could be good - but actually we'd need to know a list of styles that this package added... because maybe we needed to keep some inline styles that were already present for example.

**Comment by Stanko** [comment]
Yeah, you are totally right, I will try to figure something out. If you have ideas, shoot!

**Comment by ChrisSargent** [comment]
I would probably read and cache the styles that are on the element at the start of the transition, then add the styles you need whilst it's transitioning, then just put the original styles back on that were cached.

**Comment by Stanko** [comment]
As overflow was the only property with this issue (component was overriding it), I fixed it [here](https://github.com/Stanko/react-animate-height/commit/221acd62f1e8c2f7474083567d6e9ffcbbea7bf3).
