### ISSUE TITLE
Make it possible to prevent rendering of elements when height is 0

### ISSUE THREAD

**Issue by EmmaSimon** [Stanko/react-animate-height#20]
I'd like to not render anything when the animated element is closed, but I'm having difficulty. I don't just mean CSS `display: none` or `visibility: hidden`, I want no elements there. I tried using a combination of the provided callbacks and state, but that was too slow, by the time the animation had started it was too late to swap the child elements back to what they should be when it's open. Could a prop be added that would render `null` instead of `children` if height is 0?

**Comment by Stanko** [comment]
Hello @EmmaSimon,
Having elements removed from the dom when the height is 0 would complicate animation states even further. Because of that I will not add this feature. Maybe sometime in the future, but I'm not promising anything. Although, I'm open to accepting well written PR.

May I ask in which use case you need to remove elements completely?

**Comment by EmmaSimon** [comment]
I was looking into some performance issues and was trying to determine the cause. It looks like this had no effect and I was going down the wrong path. I had some mostly broken changes but it seems like it's not worth trying to get working. Sorry for bugging you!

**Comment by Stanko** [comment]
No problem, thanks for the feedback!

**Comment by itayganor** [comment]
I just made a simple `LazyAnimateHeight` implementation for future readers:


```tsx
export function LazyAnimateHeight({height, onHeightAnimationEnd: onHeightAnimationEndProp, children, ...rest}: AnimateHeightProps) {
    const [renderChildren, setRenderChildren] = useState(height !== 0);

    function onHeightAnimationEnd(newHeight: AnimateHeightProps['height']) {
        onHeightAnimationEndProp?.(newHeight);
        if (newHeight === 0) {
            setRenderChildren(false);
        }
    }

    useUpdateEffect(() => {
        if (height !== 0) {
            setRenderChildren(true);
        }
    }, [height]);

    const shouldRenderChildren = height !== 0 ? true : renderChildren;

    return <AnimateHeight height={height} onHeightAnimationEnd={onHeightAnimationEnd} {...rest}>
        {shouldRenderChildren ? children : null}
    </AnimateHeight>;
}
```
