### ISSUE TITLE
support for percentage

### ISSUE THREAD

**Issue by naBausch** [Stanko/react-animate-height#22]
Hey @Stanko 

we have an animation where we need to change the height from `auto` to `100%` or from `0` to `100%` do you think that would be a possible addition to your plugin?

Thanks :)

**Comment by Stanko** [comment]
@naBausch I'll try to add this, but maybe you can use `100vh` if you are using it to animate to a viewport height.

**Comment by Stanko** [comment]
Added here https://github.com/Stanko/react-animate-height/commit/65a6709177aa816db511ee9f3aedae7c1675d100#diff-45efb963a7ea3e7770e69aa33f4da7e8R110

**Comment by naBausch** [comment]
Hi Stanko,

thank you so much for adding it, that's exactly what I needed. 
For the other issue I will try to provide you an example in a bit :)
