### ISSUE TITLE
Minor thing -- npm link to this repo is wrong

### ISSUE THREAD

**Issue by cymen** [Stanko/react-animate-height#25]
Looks like typo in homepage property in package.json (has `h1ttp`) or maybe it was edited on npmjs.com but it's linking to github.com/Stanko/react-plx instead of this repo.

**Comment by Stanko** [comment]
Hello @cymen,
That happened when I moved to a new workflow for this component, and I copied the stuff I use on https://stanko.github.io/react-plx/ :)

Fixed and published, cheers!
