### ISSUE TITLE
Doesn't work with content loaded via props

### ISSUE THREAD

**Issue by colinswilliams** [Stanko/react-animate-height#27]
Tried out the demo, and got it working, but then when I attempted to get it to work with a dropdown menu, with navigation that's dynamically loaded via props, since that DOM element doesn't contain a height at the time the component is initialized, it can't animate the height of something it doesn't know.

Any tips with this?

```
<AnimateHeight duration={100} height={this.state.height}>
  <ul className={styles.linkList}>
    {content.links.map(link => <li className={styles.linkListItem} key={link.name}>
      <Link to={link.href} className={styles.link}>{link.name}</Link>
        <span className={styles.subHead}>{link.subHead}</span>    
      </li>)}
  </ul>
</AnimateHeight>
```

**Comment by Stanko** [comment]
Hello @colinswilliams,
This doesn't seem like library issue, as I just made working example here:
https://codesandbox.io/s/5ym843k18k

I mocked async data using `setTimeout` but as you can see, this library doesn't really care when the content is rendered, as it calculates height when height is changed. 

Check how you change height passed to the component.

I hope the example helps.
Cheers!
