### ISSUE TITLE
Add React 16 Support

### ISSUE THREAD

**Issue by emilyrohrbough** [Stanko/react-animate-height#28]
`react-animate-height` provides support for `react  v^15.5.4`. React 16 is expected to be released soon and can currently be tested with `react 16.0.0-rc` (more information can be found on https://github.com/facebook/react/issues/10294).

`react-animate-height` is a dependency in a package in the [terra-core monorepo](https://github.com/cerner/terra-core), which will need to be React 16 compatible. From my initial assessment of our repository, it seems focus-trap behaves as expected with `react v16.0.0-rc`, but confirmed testing is needed.

**Comment by Stanko** [comment]
https://github.com/Stanko/react-animate-height/commit/5eee270ca7200fb9e6d054e2eeb12894e1b86075

**Comment by emilyrohrbough** [comment]
When can we expect a release with these changes?

**Comment by Stanko** [comment]
It is already merged and published. You can use it with react v16.
