### ISSUE TITLE
Using React.PropTypes is Deprecated.

### ISSUE THREAD

**Issue by ChrisSargent** [Stanko/react-animate-height#3]
Hi,

I'm getting this error message in my console after upgrading to React 15.5: https://facebook.github.io/react/warnings/dont-call-proptypes.html

It seems like it is being caused by this package - any suggestions how to fix?

Thanks!

Chris

**Comment by Stanko** [comment]
React team moved `React.PropTypes` to the separate package - [prop-types](https://www.npmjs.com/package/prop-types). I will update the code.

**Comment by ChrisSargent** [comment]
Cool, thanks!

**Comment by Stanko** [comment]
Fixed here https://github.com/Stanko/react-animate-height/commit/e4981b8e67036b7500bb76317fa38dcb4eafc847

I will publish it in a minute

**Comment by ChrisSargent** [comment]
This isn't fixed for me - looks like you've fixed in the `src` folder but not reflected in the `dist` folder.

**Comment by Stanko** [comment]
Hey, I'll take a look.

**Comment by Stanko** [comment]
@ChrisSargent sorry, my bad I though `npm run release` would build it as well, but it needs to be done by hand. Should be fixed now.
