### ISSUE TITLE
Peer dependency to react 16

### ISSUE THREAD

**Issue by gpbl** [Stanko/react-animate-height#30]
Hi! 👋 

This component works well with react 15 – is there a reason for a peer dependency to React ^16?

**Comment by Stanko** [comment]
Hello @gpbl,
You are totally right, I'll fix that during the day.
Cheers!

**Comment by Stanko** [comment]
Fixed here: https://github.com/Stanko/react-animate-height/commit/a258380f08430cd87c510b8a6177b9b132165328 Pushed to the npm as well.

I used latest stable 15.x version as the peer dependency (15.6.2).

**Comment by gpbl** [comment]
thanks a lot ❤️
