### ISSUE TITLE
Percentage on initial render

### ISSUE THREAD

**Issue by andrew-morin** [Stanko/react-animate-height#31]
Issue #22 added support for percentage, but it was only added to `componentWillReceiveProps`. We have a use case where we need the height to be '100%' on first render, but the constructor still only checks for a number. Could you add the percentage check to the constructor as well? Thanks.

**Comment by Stanko** [comment]
Hello @andrew-morin,
Atm I’m kinda overwhelmed with work, but I’ll get to next week. It would be awesome if you can open a PR for it.

**Comment by Stanko** [comment]
Merged and released to npm, thank you!
