### ISSUE TITLE
prop type `applyInlineTransitions` is invalid

### ISSUE THREAD

**Issue by xMartin** [Stanko/react-animate-height#34]
Using 0.10.6 I get the following warning:
```
Warning: Failed prop type: AnimateHeight: prop type `applyInlineTransitions` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
    in AnimateHeight...
```
0.10.5 works fine.

My code looks something like this:
```
<AnimateHeight height={this.props.expanded ? 'auto' : '0'} duration={150}>
  ...
</AnimateHeight>
```

Could be related to https://github.com/Stanko/react-animate-height/pull/33

**Comment by Stanko** [comment]
Hello @xMartin,
Good catch, we used `PropTypes.boolean` instead of `PropTypes.bool`. I'll fix and release soon.

**Comment by Stanko** [comment]
Fixed and published
https://github.com/Stanko/react-animate-height/commit/3e07e93c1ea560fa67f414b65451cb6024ff3e3a
