### ISSUE TITLE
onAnimationEnd callback should be executed after content is hidden

### ISSUE THREAD

**Issue by tubalmartin** [Stanko/react-animate-height#35]
First of all, thanks for this lib!

I think `onAnimationEnd` callback should be executed after content is hidden because one may need to remove the content on the callback itself. I've just encountered this issue myself.

Right now, it is not possible to remove the animated content inside the `onAnimationEnd` callback in a synchronous way since your lib will complain when trying to access `this.contentElement` to hide the removed content.

![captura de pantalla 2017-10-25 a las 18 33 32](https://user-images.githubusercontent.com/522838/32010812-180d5b06-b9b3-11e7-8db4-759403d65a5d.png)

By shifting the order in which content is hidden and `onAnimationEnd` callback is executed, we get the best of both worlds, don't you think?

To workaround this limitation I'm making the removal operation asynchronous so your lib can hide content before removal but it's a bit hacky for my taste.

Ping me if you want me to make a PR for you.

**Comment by Stanko** [comment]
Hey, yeah that makes sense. I will look into it, and get back to you in few days. Thanks!

**Comment by Stanko** [comment]
Well I don't know how do you remove content, but this example works for me:

```js
<AnimateHeight
  height={ height }
  className='demo demo-1'
  onAnimationEnd={ () => {
    if (height === 0) {
      this.setState({ hide: true });
    }
  } }
  onAnimationStart={ () => {
    if (height > 0) {
      this.setState({ hide: false });
    }
  } }
>
  { !hide && <div className='demo-content'>
    some fancy content
  </div> }
</AnimateHeight>
```

But it still makes sense to move callbacks after hiding the content, I'll fix and publish that soon.

**Comment by tubalmartin** [comment]
Oh I was not clear enough: I do not remove some content inside the animated component...I remove/unmount the whole component wrapped in <AnimateHeight>.from the DOM.

Think of dynamic list where when an item is clicked to be deleted, the item height animates until it's hidden from sight and the item itself is removed from the list/DOM.

**Comment by Stanko** [comment]
Thanks for clarification 🙂 

I just pushed new version to npm, check the commit https://github.com/Stanko/react-animate-height/commit/29c2c629c08cebb6355ce6d3bc1e79d18fcb7933

**Comment by jakoandersen** [comment]
Hello @Stanko 
For some reason, [your snippet](https://github.com/Stanko/react-animate-height/issues/35#issuecomment-339458751) is not working when using `height = 'auto'` 

If i use for example `200` instead of auto, and change the ìf` to say as yours do: `height > 0` the animation works, and the elements are unmounted and mounted. But my content has a dynamic height, hence the `'auto'` part. 

I should also say that it is the animation that is not occurring, as i can see that the elements are unmounted and mounted. This content is never shown.

```typescript
interface Props {
    dispatch: any;
    groupOption: GroupOption;
    condition: boolean;
}

interface State {
    hide: boolean;
}

class GroupConditionContainer extends React.PureComponent<Props, State> {

    constructor(props: Props) {
        super(props);
        this.state = {
            hide: !props.condition
        };
    }

    render() {
        const height = this.props.condition ? 'auto' : 0;
        return (
            <AnimateHeight
                duration={500}
                height={height}
                animateOpacity={true}
                onAnimationEnd={() => {
                    if (height === 0) {
                        this.setState({ hide: true });
                    }
                }}
                onAnimationStart={() => {
                    if (height === 'auto') {
                        this.setState({ hide: false });
                    }
                }}
            >
                {!this.state.hide && this.props.children}
            </AnimateHeight>
        );
    }
}
```

**Comment by Stanko** [comment]
Try this:
https://codesandbox.io/s/mm6yy0llv9

I was writing the previous snippet out of my head. But thank you, as I discovered a tiny bug I introduced with v2.

Cheers!

**Comment by jakoandersen** [comment]
Works like a charm, thank you once again!
