### ISSUE TITLE
Can't start with height different than `auto`

### ISSUE THREAD

**Issue by FezVrasta** [Stanko/react-animate-height#36]
https://codesandbox.io/s/olmwx35wky

As you see from the example, the initial state will always be `auto`, and only after you toggle it twice you get it to `100%`.

Is this a known bug? Any workaround available?

**Comment by Stanko** [comment]
Hello @FezVrasta,
When you are using percentage based height, parent must have height defined. It is how CSS works. If you want to use window height, use [viewport units](https://www.sitepoint.com/css-viewport-units-quick-start/) - `100vh` in this case.

Parent height defined: 
https://codesandbox.io/s/0y9rynkjyn

Viewport units:
https://codesandbox.io/s/jpvr9x4opw

Hope that helps!

**Comment by FezVrasta** [comment]
No that's not the problem, anyway, the div managed by react-animate-height, will have a `auto` height by default, and only after two toggles, it will get `100%`

https://codesandbox.io/s/0q7p8no7zn

**Comment by FezVrasta** [comment]
![auto](https://user-images.githubusercontent.com/5382443/32377966-aeec59ee-c0a9-11e7-8bc4-aea099da2c7d.gif)

**Comment by Stanko** [comment]
Oh, sorry, I see what you mean. I'll take a look.

**Comment by Stanko** [comment]
@FezVrasta it has been fixed, you just need to update it to the latest version `0.10.8`

https://codesandbox.io/s/m3jk2jzo9x

Sorry for misunderstanding 🙃

**Comment by FezVrasta** [comment]
Oh! My bad! Thank you
