### ISSUE TITLE
Let you specify top level element

### ISSUE THREAD

**Issue by djkz** [Stanko/react-animate-height#38]
Would love to be able to animate different elements, for example <tr> or <ul>, instead of wrapping the whole thing into the div.

Possible solutions:

1. Pass element name as a prop, `<AnimateHeight element='tr'> <td>...</td></AnimateHeight>` 

2. Clone child element and pass props to it ` <AnimateHeight clone={true}><tr><td>...</td></tr></AnimateHeight>`

Both should result in `<tr aria-hidden="false" class="rah-static rah-static--height-auto" style="height: auto;"><td>...</td></tr>`

**Comment by Stanko** [comment]
Hello @djkz,

Unfortunately, `AnimateHeight` needs to have to elements top level elements. First one which has overflow hidden and which height gets animated. And the second one is the wrapper around content which is used to determine content's height. So in case of `tr` it would produce something like:

```html
<tr>
  <div> <!-- content -->
    <td>...</td>
  </div>
</tr>
```

And not just that, but using `tr` which has `display: table-cell` may introduce unexpected behaviour (same goes for other non-block elements).

Library can be rewritten to clone element outside of the viewport and do calculations on that clone element, but that it approach I really don't want to take (and I would to rewrite the library). 

If you figure out elegant (React) way of doing this, please let me know.

Cheers!
