### ISSUE TITLE
Open Peer Dependencies for React 15 || 16

### ISSUE THREAD

**Issue by emilyrohrbough** [Stanko/react-animate-height#40]
Issue https://github.com/Stanko/react-animate-height/issues/28 was logged for React 16 Support. This was marked as resolved and it appears test are being ran against React 16, however the [peer dependencies](https://github.com/Stanko/react-animate-height/blob/master/package.json#L67) are specified as 
```
 "peerDependencies": {
    "react": ">=15.6.2",
    "react-dom": ">=15.6.2"
  },
```
These should be updated for both 15 & 16.

```
 "peerDependencies": {
    "react": ">=15.6.2 || ^16.0.0",
    "react-dom": ">=15.6.2  || ^16.0.0"
  },
```
Otherwise you receive the following npm warnings when install react-animate-height:
![screen shot 2018-02-23 at 1 11 50 pm](https://user-images.githubusercontent.com/14099737/36612077-2399f136-189b-11e8-9069-216839855da6.png)

**Comment by Stanko** [comment]
Hello @emilyrohrbough,
I'm using it on the multiple projects with react 16, and I don't get these warnings. I see you are using `0.9.13` which uses these `peerDependencies`

```
  "peerDependencies": {
    "react": "^15.5.4",
    "react-dom": "^15.5.4"
  },
```

Please try updating to the latest version.

**Comment by emilyrohrbough** [comment]
@Stanko This is still an issue. The peer dependencies specified in the package.json are not open to react 16 so according to this specification, npm throws warning on the install when using React 16. This issue should not be closed.

**Comment by Stanko** [comment]
https://github.com/Stanko/react-animate-height/pull/43#issuecomment-371054146
