### ISSUE TITLE
"no dependency" is misleading

### ISSUE THREAD

**Issue by styfle** [Stanko/react-animate-height#42]
The readme says "Lightweight, **no dependency** React component..."
But I see 2 dependencies in [package.json](https://github.com/Stanko/react-animate-height/blob/master/package.json)

```
"dependencies": {
    "classnames": "^2.2.5",
    "prop-types": "^15.5.8"
  }
```

**Comment by Stanko** [comment]
Hey @styfle,
My bad, that is a left over from the first version.

On the other hand, if you are worried about pulling a lot of things, `classnames` is ~50 lines of code, and `prop-types` is pretty much a default dependency for any React component.

I'll update the documentation.

Cheers!

**Comment by Stanko** [comment]
https://github.com/Stanko/react-animate-height/commit/a1c84e3daee818a1d0c7aacf916d07047f3b13c6

**Comment by styfle** [comment]
Thanks for the response!

I noticed you provide [types](https://github.com/Stanko/react-animate-height/blob/master/source/index.d.ts).
Have you thought about writing the source code in TypeScript?
Then you could avoid prop-types altogether.

**Comment by Stanko** [comment]
You are welcome.

Not really, types were outside contribution.
