### ISSUE TITLE
calc() support?

### ISSUE THREAD

**Issue by pietrofxq** [Stanko/react-animate-height#44]
Is there a way to make it work with css calc()? Or do I need to calculate height by getting the element/window sizes?

**Comment by Stanko** [comment]
Hello @pietrofxq,
Unfortunately, this library doesn't support `calc`. It would be really cumbersome to implement parsing, window resize, em/rem changes and other edge cases. So you have to get the element height on your own and pass it to the component.

Hope that helps, cheers!
