### ISSUE TITLE
All component show, how to set only one?

### ISSUE THREAD

**Issue by vctqs1** [Stanko/react-animate-height#45]
I have many component react-animate-height so when I click button have function onClick is all component show.

                           `<tr key={key} className="user">
                                <td>{user.id}</td>
                                <td class="col-md-2">{fullName}</td>
                                <td>{user.username}</td>
                                <td class="col-md-1">{user.idNumber}</td>
                                <td>{user.birthday}</td>
                                <td class="col-md-4">{address}</td>
                                <td><DeleteButton deleteRow={this.deleteRow} key={key} id={user.id}/></td>
                                <td><UpdateButton updateRow={this.updateRow} key={key} id={user.id} toggle={this.toggle} component={this.updateUsers}/></td>
                            </tr>,
                            <tr key={user.id} className="user" data-id={user.id}>
                                <td colSpan="8">
                                    <UpdateUsers height={this.state.height}/>
                                </td>
                            </tr>`

**Comment by Stanko** [comment]
Hello @vctqs1,
This isn't issue with library but with your React knowledge.

You are using same variable `this.state.height` for all of the `<AnimateHeight>` components. Each one of them needs separate value. Check the example in the documentation:

https://github.com/Stanko/react-animate-height/blob/master/docs/docs.js#L11-L15

Cheers!
