### ISSUE TITLE
Add option to animate opacity

### ISSUE THREAD

**Issue by bdwain** [Stanko/react-animate-height#46]
First off, thanks for the awesome library.  This is so easy to use and solves such a common problem.

I was wondering if it would be possible to add an option to animate opacity. It's not THAT difficult to do using contentClassName, but you do have to duplicate the easing functions and durations, which this would help avoid. I feel like it's a pretty common way to make this kind of animation look smoother, so it seems worth building in functionality to do it.

If that sounds reasonable, I'd be happy to put together a PR. Thanks!

**Comment by Stanko** [comment]
Hello @bdwain,
My first reaction was "it can be done by adding a css class" 🙃, but then I started thinking more about it, and it makes sense to be a part of the library.

I'm working on it, and I will release it EOD probably.

Cheers!

**Comment by Stanko** [comment]
https://github.com/Stanko/react-animate-height/commit/082307a9528aa05f16bab66aece28176eba97449 🎉

**Comment by bdwain** [comment]
Thanks for releasing that so quickly!
