### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by gpbl** [Stanko/react-animate-height#48]
Congrats for v1 @Stanko! 🎉
Would you consider to [add a changelog](https://keepachangelog.com) to help us when upgrading? Thanks 🙏🏽

**Comment by Stanko** [comment]
Hello @gpbl and thank you!
I will keep that in mind and add it with the next release.

Meanwhile you can use commit messages as a workaround, I'm trying to keep them explanatory
https://github.com/Stanko/react-animate-height/commits/master

**Comment by Stanko** [comment]
https://github.com/Stanko/react-animate-height/blob/master/CHANGELOG.md 🎉

**Comment by gpbl** [comment]
Awesome ❤️ Thanks!
