### ISSUE TITLE
Delay height after opacity transition

### ISSUE THREAD

**Issue by flip-it** [Stanko/react-animate-height#49]
I would love to have the option to delay height transition to after the opacity is done.

I use this library to collapse items in a list. It would be calmer if the fading out happened before collapsing.

What do you think?

**Comment by Stanko** [comment]
Hello @flip-it,
Unfortunately I feel like that shouldn't be part of the library itself. You can write a simple wrapper though, here is simple live example:

https://codesandbox.io/s/mqqxy7ojmy

Cheers!
