### ISSUE TITLE
Fixed header disappearing on animation

### ISSUE THREAD

**Issue by BenChirlin** [Stanko/react-animate-height#50]
Loving the library but for some reason whenever my element is animated in from zero to auto height it's causing my fixed position header to disappear till the animation is complete. Guessing it might have to do with the scroll or something? I'm using the library component as follows where I have a `isToggleOn` state that changes when a user clicks a button:

```
<AnimateHeight duration={500} height={this.state.isToggleOn ? 'auto' : 0}>
  <div className='shelf-wrapper'>
    <div className='synopsis' dangerouslySetInnerHTML={{__html: synopsis}} />
  </div>
</AnimateHeight>
```

Any idea why this might be happening? If I remove the `AnimateHeight` component and simply use the state to toggle an inline style from `display: none` to `display: block` the issue goes away so it has something to do with the animation. Any other props/options I can try to solve this?

**Comment by BenChirlin** [comment]
Looks like it might be a [Chrome bug](https://stackoverflow.com/questions/11258877/fixed-element-disappears-in-chrome/29089268)? Adding:

```
overflow: hidden;
transform: translateZ(0);
z-index: 10;
```

to the element looks to have fixed it. Apparently by forcing Chrome to use hardware acceleration on the element (haven't done any cross-browser testing yet so wish me luck!).

**Comment by Stanko** [comment]
Hey @BenChirlin,
That is infamous webkit bug, I've seen it happening on Safari as well (I even wrote on my [blog](https://stanko.github.io/ios-safari-scoll-position-fixed/) about it). Forcing hardware acceleration would always solve it in my cases, but if you find more elegant workaround, please let me know.

Cheers!

**Comment by BenChirlin** [comment]
Gah now I'm getting a [likely] related issue where after opening/closing a `AnimateHeight` element my header, which I'm resizing with scroll, won't repaint when I scroll back up. But if I inspect in developer tools and hover over the element there it then repaints and pops back. What a pain!

**Comment by Stanko** [comment]
Yep, it gets frustrating :/ in the future it is really helpful if you can create a simple demo on https://codesandbox.io or https://codepen.io 
It makes things much easier to debug.
