### ISSUE TITLE
Add support for vh

### ISSUE THREAD

**Issue by kamronbatman** [Stanko/react-animate-height#53]
I tried to set height to 100vh and it defaulted to 'auto'. Would be great to see support for VH measurements.

**Comment by kamronbatman** [comment]
I think this might actually be a bug: https://github.com/Stanko/react-animate-height/blob/master/source/AnimateHeight.js#L132 should be `nextProps.height`?

**Comment by Stanko** [comment]
Unfortunately I gave this feature a lot of thinking and decided not to include it in the library. And here is why.

When a vh prop is passed (let's say `50vh`) library has to extract the number (50 in this case). Then it needs to calculate it - `window.innerHeight / 100 * 50` and animate to that specific height. In order for this to work properly, library would need to track resize events as well, and when `window.innerHeight` has changed to update he height. This complicates things and bloats the library, therefore I think it shouldn't be part of it. 

Plus it can be easily achieved outside of it, by passing property like this:
```
<AnimateHeight
  height={ window.innerHeight / 0.30 }
>
```

Again if you want it dynamically updated, make sure you re-render on window resize event.

Hope that helps, cheers!

**Comment by kamronbatman** [comment]
Yeah that is exactly what I have had to do here and in other places. Unfortunately listening to resize events is not the greatest for performance in general.
