### ISSUE TITLE
Add a warning for styles that might break the animation

### ISSUE THREAD

**Issue by Stanko** [Stanko/react-animate-height#55]
Readme already has a warning

> **style**: object
> 
> CSS style object, it will be merged with inline styles of the component
> 
> **Please note that you shouldn't apply properties that are messing with the layout (like display, height...), as these might break height calculations**

but it should be logged if user passes `style.height`, `style.display` which may break the animation.

**Comment by bjszd** [comment]
I was thinking if it would also be possible for the type definition to help warn the user.

I think you can declare this using Exclude:
https://www.typescriptlang.org/docs/handbook/utility-types.html#excludetu

So here:
https://github.com/Stanko/react-animate-height/blob/562f742aa1dfa08de64914b5c5464a4677b8f2ae/source/index.d.ts#L29

Would be something like
```typescript
type CSSPropertiesBlacklist = {
  display: string;
  height: string;
};

style?: Exclude<CSSProperties, CSSPropertiesBlacklist>
```

**Comment by Stanko** [comment]
That is a cool way to do it, I'll look into it. Thank you!

**Comment by Stanko** [comment]
Better late than never 🙈 
Fixed in https://github.com/Stanko/react-animate-height/commit/762058a6153f59f18a6a1e8b64135ec62b024993
