### ISSUE TITLE
Transition when actual height of height 'auto' element changes

### ISSUE THREAD

**Issue by cbranch101** [Stanko/react-animate-height#56]
Thanks for the super useful component, this really solves a problem for us. 

One improvement that would help a lot though is the ability to trigger the animation when, even though the height being provided to the component hasn't changed(i.e, it's just still auto) but the actual height of the element has.

**Comment by Stanko** [comment]
Hello @cbranch101,
What you are describing is out of scope for this component. For that to work, component would need to track `children` prop changes, resize and even add dom mutation listener. That adds a lot of complexity and bloat to it. Unfortunately that is something I'm trying to avoid and keep things simple.

Cheers!

**Comment by justingrant** [comment]
@oyeanuj @cbranch101 - did you find a solution to this use-case?  I'm also looking to do this.

**Comment by msaspence** [comment]
@cbranch101 @oyeanuj @justingrant This is the solution I came up with using `react-resize-observer` if it is useful to you or anyone else who finds this issue

https://gist.github.com/msaspence/8031944aafc25e051792b0161cdd0c22
