### ISSUE TITLE
animateOpacity missing from index.d.ts

### ISSUE THREAD

**Issue by jakoandersen** [Stanko/react-animate-height#58]
This causes TypeScript to complain when compiling. Adding the property to `index.d.ts` fixes it.

**Comment by Stanko** [comment]
Hello @jakoandersen,
Can you please make a PR or at least provide me with the code snippet? I'm not really using ts.
Cheers!

**Comment by jakoandersen** [comment]
Hello @Stanko 

Simply adding the following to `AnimateHeightProps` interface:
```typescript
animateOpacity?: boolean;
```

Fixes the issue. I didn't try out the other props. 

Give me one sec.

**Comment by Stanko** [comment]
Fixed in [v2.0.2](https://github.com/Stanko/react-animate-height/commit/47db7ef6831a0f967e86a3a698f4cb29fa83f074). Thanks for checking!

**Comment by jakoandersen** [comment]
Can you publish v2.0.2 to npm as well?

**Comment by Stanko** [comment]
I already did 🎉 
https://www.npmjs.com/package/react-animate-height/v/2.0.2

**Comment by jakoandersen** [comment]
Cool, thanks. I was seeing cached results.
