### ISSUE TITLE
Don't commit build artifacts (dist and lib) to source control

### ISSUE THREAD

**Issue by Daniel15** [Stanko/react-animate-height#6]
Build artifacts (such as the `dist` and `lib` directories in this repo) don't belong in source control 😃

**Comment by Stanko** [comment]
Generally speaking you are right, but as this repo is used as a npm package, it should include production ready assets. That's why I did it this way.

It is kinda hard to have a nice workflow for releasing react components to npm, so if you have any ideas, I'm open for suggestions. Thanks!

**Comment by Daniel15** [comment]
Sorry it took me a while to reply.

For the npm package, you simply need to make sure that the build runs
before publishing. You could add it as a prepublish step if you like. Take
a look at how I handle Babel-standalone as an example, or how React works.
Neither of them have the build artifacts in source control, but  they do
have a dist directory in the resulting npm package.

You simply need to add the dist directory to gitignore but *not* npmignore.

**Comment by Stanko** [comment]
Thanks, that makes sense, I'll take a look how they do it. Btw if you can direct me to a boilerplate for developing and releasing react components to the npm, I would greatly appreciate it!

**Comment by Daniel15** [comment]
Boilerplates always seem pretty overengineered to me, so I don't have experience with them as I've never used any of them.

**Comment by kentandersen** [comment]
👍 on removing dist and lib from source code

No need for boilerplate. Just do what @Daniel15 described
1. add dist and lib to `.gitignore`, but not `.npmignore`
2. add `"prepublish": "npm run build"` to scripts in `package.json`

When you run `npm publish` dist and lib will be updated before its pushed to npm. `.gitignore` will keep them out of source control

**Comment by Stanko** [comment]
Thank you very much both of you guys. I just fixed this (https://github.com/Stanko/react-animate-height/commit/23aa3955cddf05f90a3be18afd37bd34dd1516f1) and published. `.npmignore` was the thing I was missing. 

@kentandersen thanks for the other PR as well.
