### ISSUE TITLE
Pass target height to start and end callbacks

### ISSUE THREAD

**Issue by fzembow** [Stanko/react-animate-height#63]
In a project I'm working on, I'm doing a whole bunch of absolutely-positioned elements, that themselves have height animations that can sometimes go to height: `auto`.

I found it a limitation that although internally this component knows the target height, its parents aren't aware of this. With the addition of the target height as argument passed to the `onAnimationStart` and `onAnimationEnd` functions, I could smoothly position elements even though they are also transitioning.

I'll create a PR that implements this shortly.

**Comment by Stanko** [comment]
Published as [2.0.7](https://www.npmjs.com/package/react-animate-height/v/2.0.7) 🎉 

Thank you once again!
