### ISSUE TITLE
Update react and react-dom peer dependencies to version 16

### ISSUE THREAD

**Issue by mundosk8** [Stanko/react-animate-height#66]
The react and react-dom peer dependencies still point to react 15.

**Possible Solution**

Update versions on package.json

**Your Environment**
 - Version used: 2.0.7
 - OS: MacOs
 - Browser chrome
 - Version latest

**Comment by Stanko** [comment]
Hello,
I used `>=15.6.2`, I thought it is covering v16 as well. Is it not the case?

**Comment by Stanko** [comment]
I just tried to install `react-animate-height` on a project using `react` and `react-dom` `v16.8.2`. It issued no errors or warnings, so this works as expected.

Library does support v15 and v16 so this is expected behaviour.

Cheers!
