### ISSUE TITLE
Not compatible with React-table?

### ISSUE THREAD

**Issue by naomimachado** [Stanko/react-animate-height#67]
Tried to add height animation to a subcomponent in [react-table](https://github.com/tannerlinsley/react-table). Doesn't seem to be working. Any ideas why?
Thanks!

**Comment by Stanko** [comment]
Hello,
I don't know how `react-table` works, but if you are trying to animate a `div` I don't see why it shouldn't work. However `react-animate-height` doesn't support animating `tr` elements, as it needs to add more html elements which break `table` structure.

You ignored the issue template and gave me no info on the issue or how to replicate it. So I can't help you until you create an example on https://codesandbox.io/ or a similiar service.

Cheers!

**Comment by naomimachado** [comment]
I am trying to animate tr elements. I think that's why it isn't working. Thanks anyway!
