### ISSUE TITLE
contentClassName applies undefined className

### ISSUE THREAD

**Issue by bruno-gouveia** [Stanko/react-animate-height#7]
With the recent update, if you dont pass the prop contentClassName it gives the content the class "undefined". The component should verify if the prop is passed and only apply it in that case.

It causes issues with Jest snapshot testing.

**Comment by Stanko** [comment]
Hello,
I'll get to this one, but not sure when, as I'm quite busy atm. If you can do a quick pr that would be great!
Thanks

**Comment by Stanko** [comment]
@bruno-gouveia I just tested it with react version 15.5.4 and it doesn't happen anymore, it seems react team handled it.
