### ISSUE TITLE
Animate Margin-top

### ISSUE THREAD

**Issue by decimoseptimo** [Stanko/react-animate-height#70]
The current API exposes a 'height' prop that gets you a "reveal" effect. What about a 'margin' prop for a "slide" effect.

e.g. Animating from margin-top: -auto -> margin-top: 0. `auto` could be exposed as a variable storing the container's height.

**Comment by Stanko** [comment]
Hello @decimoseptimo,
Unfortunately that is out of the scope of this library.

But is sounds you are trying to achieve something like this:
https://codepen.io/anon/pen/gydMWM

Cheers!

**Comment by decimoseptimo** [comment]
Not really. It doesn't adapt to variable height. It doesn't push content down. I think when you're already calculating height you're half way there.
