### ISSUE TITLE
Bug: Aria-hidden isn't updating, stays always with false 

### ISSUE THREAD

**Issue by nuno-andrade-ui** [Stanko/react-animate-height#71]
Aria-hidden attribute isn't updating.

Hidden Content:
<img width="658" alt="Screenshot 2019-05-16 at 15 06 55" src="https://user-images.githubusercontent.com/6398378/57860299-8d698200-77ec-11e9-94aa-bb1a73f5c17e.png">

Showing Content:
<img width="657" alt="Screenshot 2019-05-16 at 15 07 02" src="https://user-images.githubusercontent.com/6398378/57860300-8d698200-77ec-11e9-9d64-f63f243dca61.png">

**Expected behavior**

When the content is hidden it should return aria-hidden="true", when the content is shown should return aria-hidden="false". 

**Additional context**

This issue can lead to errors if you have accessibility tests in your application and not be able to pass in a CI environment

**Comment by Stanko** [comment]
Hello @nuno-andrade-ui,

Thank you for the detailed description, but I've just tried the demo https://muffinman.io/react-animate-height/ and I can't replicate it:

<img width="1263" alt="Screenshot 2019-05-16 16 12 14" src="https://user-images.githubusercontent.com/776788/57860637-8004c580-77f5-11e9-9a6d-0d3393798bfc.png">

Are you maybe using old version of the library?

Cheers!

**Comment by Stanko** [comment]
I was just able to replicate it, but I don't think it is a library issue.

`height` prop type is a number. If you pass zero as a string `"0"` if will fail to set aria hidden to `true`, you need to use a number.

```jsx
<AnimateHeight
  height="0" // it needs to be a u number 0
>
```

https://github.com/Stanko/react-animate-height/blob/master/source/AnimateHeight.js#L336

Hope that helps, cheers!

**Comment by nuno-andrade-ui** [comment]
Heu @Stanko thank you for your help, it was really that. I was passing 0 as a string, now it works perfectly, I will add a prototype check for that, for not happening again :D 

I will close now that, as this isn't really a library issue. 

One more time thank you for your help, and sorry about this! 👍

**Comment by Stanko** [comment]
No worries, I need to tighten prop type check, as `height` accepts string as well, for percentage values (ie. `"30%"` or `"90%"`). At least to drop a warning.
