### ISSUE TITLE
Box-shadows only render once the animation completes

### ISSUE THREAD

**Issue by petermikitsh** [Stanko/react-animate-height#8]
To reproduce:

- Go to [demo page](https://stanko.github.io/react-animate-height/).
- Using developer tools, go to the `.demo-content` element and add this box shadow style:

```
box-shadow: 0 6px 7px -4px rgba(0, 0, 0, 0.2), 0 11px 15px 1px rgba(0, 0, 0, 0.14), 0 4px 20px 3px rgba(0, 0, 0, 0.12);
```

Observe the box-shadow appearance at the end of the animation:

![boxshadow5](https://cloud.githubusercontent.com/assets/1571918/26566579/141ca5ee-44a9-11e7-85ea-85886517dfac.gif)

**Comment by Stanko** [comment]
Hello @petermikitsh, thanks for the feedback. Luckily this is not an issue, as you should apply `box-shadow` to the root element of the component. In the demo it has class `.demo`. As it has overflow hidden (which is crucial for animating) shadow is cut off until animation is complete.

Cheers!

**Comment by petermikitsh** [comment]
Tested out your approach, applying the box-shadow to the `.demo` node. Visually, it's not quite the treatment that I'm looking for since the box shadow is still present at 0 height. Ideally, it the shadow would progressively reveal the shadow as the content expanded. I'm not sure there's a solution because (as you said) the overflow property is key.

<img width="878" alt="screen shot 2017-05-29 at 10 57 53 pm" src="https://cloud.githubusercontent.com/assets/1571918/26569902/4f3a20de-44c2-11e7-95d5-90853a9ff501.png">

**Comment by Stanko** [comment]
I have a plan of adding animation classes, I might do it today if I squeeze it in. Something like `-animating` `-animating-up` `-animating-down` etc.  Would that help?

**Comment by petermikitsh** [comment]
I think you'd want to apply the box-shadow as the animation began, so an `-animating` css class would work. You would also want the shadow to persist once fully expanded too. I think that would work. Thanks for the quick replies.

**Comment by Stanko** [comment]
You are welcome!

Can you help me with list of classes that should be applied? I was thinking of adding classes for these states:

* animating
* animating up
* animating down
* done / static
* done - 0
* done - auto
* done - anything in between

Can you think of anything else?

**Comment by petermikitsh** [comment]
That's a good set. If you wanted to make it more flexible, you could make all of these class names configurable through props so people can use their own. In my particular project, I'm using [css modules](https://github.com/css-modules/css-modules#usage-with-preprocessors), so if the classnames were static, I'd have to wrap them in a `:global { }` block to prevent the pre-processor from compiling them to something else. Design-wise, I prefer to isolate my component implementations, so that's where the dynamic class names would be useful.

**Comment by Stanko** [comment]
CSS classes are added [here](https://github.com/Stanko/react-animate-height/commit/221acd62f1e8c2f7474083567d6e9ffcbbea7bf3).

I hope this is what you were going for (rather large gif):

![shadow-2](https://cloud.githubusercontent.com/assets/776788/26578065/ccac3b3a-452e-11e7-890b-3200dbbf2389.gif)

Please note that box shadow transition should be passed through `style` object not to be overridden in the react component. 

**CSS**
```
.demo-1.rah-static--height-specific,
.demo-1.rah-static--height-auto,
.demo-1.rah-animating--to-height-specific,
.demo-1.rah-animating--to-height-auto {
  box-shadow: 5px 5px 20px rgba(0,0,0,0.3);
}
```

**JS** 
```
<AnimateHeight
  duration={ 1000 }
  height={ height }
  className='demo demo-1'
  style={ { transition: 'box-shadow 1000ms' } }
>
```

When you check it yourself, please close the issue.

Cheers!

**Comment by Stanko** [comment]
I guess `hooray` emoji means this is fixed :) closing it!
