### ISSUE TITLE
[Question] Is proportional animation duration possible

### ISSUE THREAD

**Issue by David-Way** [Stanko/react-animate-height#80]
I'm animating in dynamic content and was wondering if there is a way to have the duration of the animation be proportional to the size of the content being animated in. For example the larger the change in size of the element, the longer the animation takes. 

Maybe having access to something like the `newHeight` argument returned by onAnimationStart, but before the animation begins if possible.

Thanks for your time.

**Comment by Stanko** [comment]
Hello @David-Way,

That is an interesting usecase. But unfortunately I don't have an idea how to implement it and still keep the same simple API. Because new height is calculated in `componentDidUpdate` and having a callback there wouldn't help much as animation is already started.

I'm open to implementation suggestions though.

Personally I would create a simple wrapper, something like this:

```jsx
import React, { Children } from 'react';
import Plx from 'react-plx';

const PlxRelativeDuration = ({ children, duration, ...props }) => {
  const childrenCount = Children.count(children);

  return (
    <Plx 
      { ...props } 
      duration={ duration * childrenCount }
    >
      { children }
    </Plx>
  );
};


export default PlxRelativeDuration;
```

I'm aware that this is not perfect (a single child could be very tall or multiple child elements could be very short) but I think it can be adapted for a specific usecase.

Cheers!

**Comment by solastley** [comment]
@Stanko thanks for making this! Super useful.

I'd also love to see a prop which sets the duration dynamically based on content height. I think there is probably a relatively simple algorithm for setting the duration in a way which is not purely static but ensures the animation speed is pleasant to most users.

I think what it comes down to is that there should be some kind of prop or props for minimum and maximum animation speed. Then you can use the height of the content to determine a duration internally which will result in the animation speed falling between those bounds.

The use cases are for content which is very small compared to normal and content which is very tall compared to normal. In these cases, the animation speed ends up being too slow or too fast, respectively. But if you could specify a min and max animation speed then that would address those cases.

**Comment by Stanko** [comment]
Hey @solastley,
I did something similar in [animated-scroll-to](https://github.com/Stanko/animated-scroll-to#options), but the difference with AnimateHeight is that it already has `duration` prop. Introducing speed, minDuration and maxDuration will complicate the code and the API. And one of `duration` or `speed` would have to override the other (as they are controlling the same thing).

It is definitely worth exploring, but I'm not sure when I'll be able to dedicate time to it.

Cheers!
