### ISSUE TITLE
[Feature Request] Disable it when auto is lower than specific height

### ISSUE THREAD

**Issue by kud** [Stanko/react-animate-height#81]
I've got this: 

```
<AnimateHeight
                          duration={300}
                          height={state.measuresExpanded ? "auto" : 80}
                        >
```

but auto here is lower than 80px.

**Comment by Stanko** [comment]
Hello @kud,
I don't understand, it behaves as expected:
https://codesandbox.io/s/react-animate-height-basic-example-x8rkt

**Comment by kud** [comment]
Hello @Stanko . 

I'm sorry I was unclear and think more and more that it's not the responsability of the lib itself to do that but. I wanted something like "toggle" button could be disable when static height value is higher than "auto", in order to disable AnimateHeight.
