### ISSUE TITLE
"Can't perform a React state update on an unmounted component"

### ISSUE THREAD

**Issue by atombender** [Stanko/react-animate-height#82]
This library currently causes React warnings to be emitted to the console:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

This happens because the library starts asynchronous updates that do not guard themselves against unmounting; specifically, [here](https://github.com/Stanko/react-animate-height/blob/265a0234350dcb898dc3408edbd6e77773b62fba/source/AnimateHeight.js#L208):

```javascript
        startAnimationHelper(() => {
          this.setState(timeoutState);
```

The component needs to track whether it's still mounted, and abort any asynchronous processing if not mounted. `componentWillUnmount()` currently appears to do this, but only for `setTimeout` calls, not `requestAnimationFrame`.

**Comment by Stanko** [comment]
Fixed with version 2.0.16, here's the commit:
https://github.com/Stanko/react-animate-height/commit/1d2324a071966677155e6b627c698b6583454d5e

And good job catching this, it never happened to me.
