### ISSUE TITLE
Feature request(ish) could you make a 0.x maint branch?

### ISSUE THREAD

**Issue by mattcrowder** [Stanko/react-animate-height#84]
Hello! I am trying to upgrade my current team to the latest version of React, and unfortunately we have a rule where no `console.warn`s can happen while running test cases.

And v0.x uses `componentWillReceiveProps`, so I would like to make a PR to v0.x to add `UNSAFE` to `componentWillReceiveProps`. 

Could you create a 0.x maint branch so I could create a PR to that branch, and then you could publish a patch with the fix?

Here is your sha: a8361ffc7f2324ea387ccef91ae5ff49c2fedcfa

**Comment by mattcrowder** [comment]
So if you look at https://github.com/reduxjs/react-redux/branches, they have separate branches for maintenance just in case they need to update v5 or v4 for security updates or anything really.

If you look at v5.x, they actually released a new version of v5 and we were able to download it. The problem is, we're not ready to download v2 right now.

**Comment by mattcrowder** [comment]
yeah I am asking: 
Do you want me to create a branch from `a8361ff` and update it to use `UNSAFE_componentWillReceiveProps`
😄 
And then you switch to that branch and you publish a new version off of it to be 0.9.14 or something,(just a patch)

**Comment by Stanko** [comment]
* the last `0.x` version is `0.10.10`
* the last `0.9.x` version is `0.9.13`

Both are compatible with React 15, and if I rename `componentWillReceiveProps` to `UNSAFE_componentWillReceiveProps` to avoid warnings, I would break compatibility with React 15.

I still don't get why you can't use version 2, or just create your own fork?

**Comment by mattcrowder** [comment]
@Stanko Thanks for your prompt reply and help, we are just going to update to version 2!
