### ISSUE TITLE
Add element id support for a11y

### ISSUE THREAD

**Issue by ling1726** [Stanko/react-animate-height#86]
This is a nice to have in order to support a11y aria attributes such as:

* https://www.w3.org/TR/wai-aria-1.1/#aria-controls
* https://www.w3.org/TR/wai-aria-1.1/#aria-describedby

PR made for this feature #85

**Comment by Stanko** [comment]
Hello @ling1726,
I’m on vacation, on my phone, but I’m pretty sure this is already supported.

https://github.com/Stanko/react-animate-height/blob/master/source/AnimateHeight.js#L352

And it is already in the documentation, check the note beneath the props.

Let me know if that works.

Cheers!

**Comment by ling1726** [comment]
Hi @Stanko .

The the documentation mentions that it's possible to pass a className to the component but there is no mention of the **id** attribute.

Likewise in the source code of the component I can't see where the **id** attribute is assigned to the first div

**Comment by Stanko** [comment]
Like I said, there is a note at the bottom of the readme:

> Additional props will be passed to the wrapper div, to make adding attrs like aria-* easier.

Basically, it will bypass *any* prop that is not used by the library itself.

Highlighted the line of code Is responsible for it.

Cheers!

**Comment by ling1726** [comment]
Hi,

Just tested that, great!

However in this case it doesn't seem to play too well with TS, would I be able to just add the type declaration to the index.d.ts file then ? I've modified the PR accordingly

**Comment by Stanko** [comment]
Cool, that makes sense. I wonder if there is more generic way to handle types for these additional props. Any ideas?

**Comment by ling1726** [comment]
I've modified the PR to use types instead and added the React.HTMLAttributes<HTMLDivElement>. That should do the trick

**Comment by Stanko** [comment]
Sweet, thank you for putting the effort! I’ll test and merge it as soon as I can.

**Comment by Stanko** [comment]
Merged and released in 2.0.17 🎉 
Thank you!
