### ISSUE TITLE
Prevent jumping when inner content unmount

### ISSUE THREAD

**Issue by user753** [Stanko/react-animate-height#87]
https://codesandbox.io/s/react-animate-height-basic-example-og48h

I would like if AnimateHeight preserve previous height and animate it even if inner content doesn't exists anymore.

**Comment by Stanko** [comment]
It is easily doable by using `onAnimationEnd` callback:
https://codesandbox.io/s/react-animate-height-basic-example-v1ml1

This is something I think shouldn't be handled by the library itself, but by the developer.

Cheers!
