### ISSUE TITLE
Callback onAnimationEnds - Feature request

### ISSUE THREAD

**Issue by m4recek** [Stanko/react-animate-height#9]
Hi,
is it possible to add a callback for animations? Something like onAnimationEnd / onAnimationStart. 

Use case is that we want to scroll the page to specific location after animation ended and element has full height.

Thank you.

**Comment by Stanko** [comment]
Hello @m4recek,
I'm working on it, I will release new version later today.

**Comment by Stanko** [comment]
Added in version 0.9.5, check the commit https://github.com/Stanko/react-animate-height/commit/bf20e5ba2f9ddc44011c6870d9f024d1e9e7b48c
