### ISSUE TITLE
Add engines to package.json

### ISSUE THREAD

**Issue by MichaelDeBoey** [Stanko/react-animate-height#91]

**Comment by Stanko** [comment]
Hey @MichaelDeBoey,
I'm open to add them, but I'm not sure what should I add as I never used them. Can you give me a little help?

Cheers!

**Comment by MichaelDeBoey** [comment]
@Stanko It's mostly the minimum `node` version you're testing against.

https://github.com/jaydenseric/apollo-upload-client/blob/219002c88a34aade4c0fd1f89865f560ac730804/package.json#L32-L34

https://github.com/facebook/react/blob/147179ae82039f38fa1a9a72402f578af8fb3ea3/packages/react/package.json#L28-L30

**Comment by Stanko** [comment]
Cool, I will test and one. Thank you!

**Comment by Stanko** [comment]
Published in 2.0.22

https://github.com/Stanko/react-animate-height/commit/7df0664f938d6a74fa0f911b712053291f984902
