### ISSUE TITLE
Support animating elements rendered using .map()

### ISSUE THREAD

**Issue by acal11** [Stanko/react-animate-height#93]
It would be great if this package was able to be extended to work on elements rendered using .map(). `react-transition-group` has the `TransitionGroup` component to make this possible, however to make it work as I like using `react-animate-height` I need to keep all 'removed' elements in-state with a `visible` flag attached to it. This means that my state is storing unrequired data, making things like `.length` more complex to calculate, and potentially causing it to be out of sync with the data source.

**Comment by Stanko** [comment]
Hey @acal11,
Can you show me the example of what are you trying to achieve? 

But I'll be honest, it sounds like something that is outside of the scope of this library. If I start tracking changes on children elements, that introduces a lot of complexity - on the top of my head, library would need to cache the fixed height and track window resize.

**Comment by acal11** [comment]
Hey @Stanko,

Basically the below - animating items as they're added or removed from an array. Without TransitionGroup, they won't out, just appear/disappear.

Like I said, I did make it work by adding `isVisible` to the item in the array and just flagging them instead of removing them, but that just makes the local state a bit messy imo. Understandable if it's too much for this library, just a thought :)

```
<TransitionGroup>
{arr.map((i, index) => (
    <Transition in key={i.id}>
    {(state): ReactElement => (
        <div
        style={{
            ...styles,
            ...transitionStyles[state],
        }}
        >
        /** list of components mapped from arr that I want to animate in/out as they appear/disappear from arr **/
        </div>
    )}
    </Transition>
))}
</TransitionGroup>
```

**Comment by Stanko** [comment]
Unfortunately, that is outside of the scope of `AnimateHeight`. You could write a `AnimatedList` but it gets pretty complicated as you need to track `props.children` changes and to clone elements to keep them in state while they are animated out.

But this example from `react-transition-group` seems to be very close to what you are trying to achieve:
http://reactcommunity.org/react-transition-group/transition-group

It needs to be tweaked to animate height instead of opacity, but it seems like a good start for me.

**Comment by acal11** [comment]
Just a quick update for anyone who may come across this in the future:

Making it work with `TransitionGroup` is actually straight forward. It just requires creating a wrapper around `AnimateHeight` which accepts an `in` prop (which is what `TransitionGroup` controls), and then using this to set `AnimateHeight`'s `height` prop accordingly.
